
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150326 (SVN rev 63)
//----------------------------------------------------

package edu.uta.spl;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int STRING_LITERAL = 3;
  public static final int UMINUS = 53;
  public static final int SEMI = 43;
  public static final int INT = 19;
  public static final int ARRAY = 7;
  public static final int FOR = 17;
  public static final int MINUS = 33;
  public static final int NOT = 22;
  public static final int AND = 6;
  public static final int LT = 36;
  public static final int TYPE = 29;
  public static final int LP = 47;
  public static final int OR = 23;
  public static final int COMMA = 44;
  public static final int RP = 48;
  public static final int DIV = 11;
  public static final int GEQ = 39;
  public static final int LSB = 51;
  public static final int LOOP = 20;
  public static final int PLUS = 32;
  public static final int EXIT = 14;
  public static final int IF = 18;
  public static final int DOT = 46;
  public static final int ID = 2;
  public static final int EOF = 0;
  public static final int BOOLEAN = 8;
  public static final int LB = 49;
  public static final int RETURN = 26;
  public static final int EQUAL = 13;
  public static final int TRUE = 35;
  public static final int BY = 9;
  public static final int error = 1;
  public static final int RB = 50;
  public static final int MOD = 21;
  public static final int NEQ = 41;
  public static final int EQ = 40;
  public static final int TIMES = 34;
  public static final int COLON = 42;
  public static final int SHARP = 45;
  public static final int ELSE = 12;
  public static final int RSB = 52;
  public static final int READ = 25;
  public static final int TO = 28;
  public static final int WHILE = 31;
  public static final int FLOAT = 16;
  public static final int LEQ = 37;
  public static final int STRING = 27;
  public static final int DEF = 10;
  public static final int FLOAT_LITERAL = 5;
  public static final int FALSE = 15;
  public static final int GT = 38;
  public static final int VAR = 30;
  public static final int PRINT = 24;
  public static final int INTEGER_LITERAL = 4;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ID",
  "STRING_LITERAL",
  "INTEGER_LITERAL",
  "FLOAT_LITERAL",
  "AND",
  "ARRAY",
  "BOOLEAN",
  "BY",
  "DEF",
  "DIV",
  "ELSE",
  "EQUAL",
  "EXIT",
  "FALSE",
  "FLOAT",
  "FOR",
  "IF",
  "INT",
  "LOOP",
  "MOD",
  "NOT",
  "OR",
  "PRINT",
  "READ",
  "RETURN",
  "STRING",
  "TO",
  "TYPE",
  "VAR",
  "WHILE",
  "PLUS",
  "MINUS",
  "TIMES",
  "TRUE",
  "LT",
  "LEQ",
  "GT",
  "GEQ",
  "EQ",
  "NEQ",
  "COLON",
  "SEMI",
  "COMMA",
  "SHARP",
  "DOT",
  "LP",
  "RP",
  "LB",
  "RB",
  "LSB",
  "RSB",
  "UMINUS"
  };
}

